fix(lang): use correct current version when checking for outdated dune
Previously, we would output the version we were parsing which led to
nonsensical error messages like:

```
File "dune-project", line 1, characters 11-18:
  1 | (lang dune 123.123)
                 ^^^^^^^
  Error: Version 123.123 of the dune language is not supported.
  Supported versions of this extension in version 123.123 of the dune language:
  - 1.0 to 1.12
  - 2.0 to 2.9
  - 3.0 to 3.20
```

We fix this by passing the current supported version of dune lang
instead of the one we just parsed, allowing the error message to
beceome:

```
  File "dune-project", line 1, characters 11-18:
  1 | (lang dune 123.123)
                 ^^^^^^^
  Error: Version 123.123 of the dune language is not supported.
  Supported versions of this extension in version 3.20 of the dune language:
  - 1.0 to 1.12
  - 2.0 to 2.9
  - 3.0 to 3.20
```

The error message is still a bit nonsensical due to us mentioning
extensions here, but that will be left as a future improvement.

Signed-off-by: Ali Caglayan <alizter@gmail.com>