fix: Allow `package` in any location in `rule` (#7445)
While fixing the package associations in ocaml/opam#5496 I realized that the package stanza is only accepted when it is at the end of the rule stanza.

* Add test that `packages` needs to be last, or it will be rejected

    File "dune", line 12, characters 3-10:
    12 |   (package a)
            ^^^^^^^
    Error: Unknown action or rule field.
    [1]

Signed-off-by: Marek Kubica <marek@tarides.com>
Co-authored-by: Etienne Millon <me@emillon.org>