fix: fix breaking after Error:
Due to the way paragraphf is boxed, we would get:

```
Error:
Foo bar is baz.
```

rather than
```
Error: Foo bar is baz.
```

Signed-off-by: Ali Caglayan <alizter@gmail.com>