Add test that `packages` needs to be last, or it will be rejected
    File "dune", line 12, characters 3-10:
    12 |   (package a)
            ^^^^^^^
    Error: Unknown action or rule field.
    [1]

Signed-off-by: Marek Kubica <marek@tarides.com>