Show a hint when trying to build something excluded by a `dirs` stanza. (#13919)
Have you ever tried to `dune build a/b/c` only for dune to respond that
"Don't know how to build a/b/c", while you absolutely have an "a/b/dune"
file that definitely has a rule to build "c", prompting you to angrily
shake your fist at the screen while wondering what kind of sorcery is
causing this, before discovering 10 exhausting minutes later that "a/b"
was excluded by a "dirs" stanzas, making dune's error message not untrue
per se, but borderline maliciously unhelpful?

<img width="250" height="300" alt="image"
src="https://github.com/user-attachments/assets/5731a0d1-8d66-4e87-a239-47a61a43cf5c"
/>

Well, I do sometime, and I just did.

This MR adds a hint in such a case that one of the parent directory was
ignored, with the location of the `dirs` stanzas. It should not change
anything outside of the error case, especially not impact performance.

```
$ dune build A/a
Error: Don't know how to build A/a
Hint: directory A exists on disk but is excluded by a (dirs ...) stanza at
dune:1
$
```

---------

Signed-off-by: mefyl <mefyl@gruntech.org>